In [3]:
#load all data so far
import pandas as pd

path = "C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\3IDs.csv"
id_table = pd.read_csv(path)
id_table.head()

   hoopR_ID         athlete  nba_api_ID  pst_ID
0       136    Vince Carter        1713     184
1       165  Jamal Crawford        2037     458
2       272   Manu Ginobili        1938     165
3       609   Dirk Nowitzki        1717      33
4       841     Jason Terry        1891     252

In [5]:
path = "C:\\Users\\oscar\\big_ahh_files\\hoopR_all_games.csv"
all_games = pd.read_csv(path)
all_games.head()

C:\Users\oscar\AppData\Local\Temp\ipykernel_20044\451681907.py:2: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  all_games = pd.read_csv(path)

,Unnamed: 0,game_id,season,season_type,game_date,game_date_time,athlete_id,athlete_display_name,team_id,team_name,...,team_score,opponent_team_id,opponent_team_name,opponent_team_location,opponent_team_display_name,opponent_team_abbreviation,opponent_team_logo,opponent_team_color,opponent_team_alternate_color,opponent_team_score
0,0,400975976,2018,2,2018-04-11,2018-04-11 22:30:00,136,Vince Carter,23,Kings,...,96,10,Rockets,Houston,Houston Rockets,HOU,https://a.espncdn.com/i/teamlogos/nba/500/hou.png,D40026,c4ced3,83
1,1,400975956,2018,2,2018-04-09,2018-04-09 20:30:00,136,Vince Carter,23,Kings,...,85,24,Spurs,San Antonio,San Antonio Spurs,SA,https://a.espncdn.com/i/teamlogos/nba/500/sa.png,000000,061922,98
2,2,400975934,2018,2,2018-04-06,2018-04-06 20:00:00,136,Vince Carter,23,Kings,...,94,29,Grizzlies,Memphis,Memphis Grizzlies,MEM,https://a.espncdn.com/i/teamlogos/nba/500/mem.png,5D76A8,7399c6,93
3,3,400975913,2018,2,2018-04-03,2018-04-03 22:00:00,136,Vince Carter,23,Kings,...,94,21,Suns,Phoenix,Phoenix Suns,PHX,https://a.espncdn.com/i/teamlogos/nba/500/phx.png,23006a,f1f2f3,97
4,4,400975901,2018,2,2018-04-01,2018-04-01 21:30:00,136,Vince Carter,23,Kings,...,84,13,Lakers,Los Angeles,Los Angeles Lakers,LAL,https://a.espncdn.com/i/teamlogos/nba/500/lal.png,542582,552582,83

In [419]:
path = "C:\\Users\\oscar\\big_ahh_files\\injuries.csv"
injuries = pd.read_csv(path)
injuries.head()

,Date,Team,Acquired,Relinquished,Notes,player_id
0,2016-01-01,Hornets,NaN,Al Jefferson,placed on IL recovering from surgery on right ...,133
1,2016-01-01,Mavericks,NaN,Devin Harris,back spasms (DTD),19
2,2016-01-01,Mavericks,NaN,Justin Anderson,placed on IL,4
3,2016-01-01,Raptors,Bruno Caboclo,NaN,activated from IL,0
4,2016-01-02,Cavaliers,Kyrie Irving,NaN,activated from IL,1

In [99]:
path = "C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\nba_api_player_info.csv"
player_info = pd.read_csv(path)
player_info.head()

,Unnamed: 0,PERSON_ID,FIRST_NAME,LAST_NAME,DISPLAY_FIRST_LAST,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FI_LAST,PLAYER_SLUG,BIRTHDATE,SCHOOL,...,PLAYERCODE,FROM_YEAR,TO_YEAR,DLEAGUE_FLAG,NBA_FLAG,GAMES_PLAYED_FLAG,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,GREATEST_75_FLAG
0,0,1713,Vince,Carter,Vince Carter,"Carter, Vince",V. Carter,vince-carter,1977-01-26T00:00:00,North Carolina,...,vince_carter,1998,2019,N,Y,Y,1998,1,5,N
1,1,2037,Jamal,Crawford,Jamal Crawford,"Crawford, Jamal",J. Crawford,jamal-crawford,1980-03-20T00:00:00,Michigan,...,jamal_crawford,2000,2019,N,Y,Y,2000,1,8,N
2,2,1938,Manu,Ginobili,Manu Ginobili,"Ginobili, Manu",M. Ginobili,manu-ginobili,1977-07-28T00:00:00,Virtus Bologna,...,manu_ginobili,2002,2017,N,Y,Y,1999,2,57,N
3,3,1717,Dirk,Nowitzki,Dirk Nowitzki,"Nowitzki, Dirk",D. Nowitzki,dirk-nowitzki,1978-06-19T00:00:00,DJK Wurzburg,...,dirk_nowitzki,1998,2018,N,Y,Y,1998,1,9,Y
4,4,1891,Jason,Terry,Jason Terry,"Terry, Jason",J. Terry,jason-terry,1977-09-15T00:00:00,Arizona,...,jason_terry,1999,2017,N,Y,Y,1999,1,10,N

In [279]:
path = "C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\arenas_and_airports.xlsx"
arenas = pd.read_excel(path)
arenas.head()

,team,arena,arena_start,arena_coor,nearest_airport,airport_coor
0,Kings,Golden 1 Center,2016-10-01,38°34′49.3″N 121°29′58.6″W,Sacramento International Airport,38°41′44″N 121°35′27″W
1,Hawks,State Farm Arena,1999-10-01,33°45′26″N 84°23′47″W,Hartsfield-Jackson International Airport,33°38′12″N 84°25′41″W
2,Timberwolves,Target Center,1990-10-01,44°58′46″N 93°16′34″W,Minnesota-Saint Paul International Airport,44°52′55″N 093°13′18″W
3,Suns,Footprint Center,1992-10-01,33°26′45″N 112°4′17″W,Phoenix Sky Harbor International Airport,33°26′03″N 112°00′42″W
4,Nets,Barclays Center,2012-10-01,40°40′57.58″N 73°58′30.81″W,John F Kennedy International Airport,40°38′23″N 73°46′44″W

In [101]:
#create player_dim table from nba_api_player_info
#decided to make the nba_api ID the definitive player ID
player_dim = player_info[['PERSON_ID']]
player_dim = player_dim.rename(columns={'PERSON_ID':'player_key'})
player_dim = pd.concat([player_dim, player_info.iloc[:, 2:]], axis=1)
player_dim.head()

,player_key,FIRST_NAME,LAST_NAME,DISPLAY_FIRST_LAST,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FI_LAST,PLAYER_SLUG,BIRTHDATE,SCHOOL,COUNTRY,...,PLAYERCODE,FROM_YEAR,TO_YEAR,DLEAGUE_FLAG,NBA_FLAG,GAMES_PLAYED_FLAG,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,GREATEST_75_FLAG
0,1713,Vince,Carter,Vince Carter,"Carter, Vince",V. Carter,vince-carter,1977-01-26T00:00:00,North Carolina,USA,...,vince_carter,1998,2019,N,Y,Y,1998,1,5,N
1,2037,Jamal,Crawford,Jamal Crawford,"Crawford, Jamal",J. Crawford,jamal-crawford,1980-03-20T00:00:00,Michigan,USA,...,jamal_crawford,2000,2019,N,Y,Y,2000,1,8,N
2,1938,Manu,Ginobili,Manu Ginobili,"Ginobili, Manu",M. Ginobili,manu-ginobili,1977-07-28T00:00:00,Virtus Bologna,Argentina,...,manu_ginobili,2002,2017,N,Y,Y,1999,2,57,N
3,1717,Dirk,Nowitzki,Dirk Nowitzki,"Nowitzki, Dirk",D. Nowitzki,dirk-nowitzki,1978-06-19T00:00:00,DJK Wurzburg,Germany,...,dirk_nowitzki,1998,2018,N,Y,Y,1998,1,9,Y
4,1891,Jason,Terry,Jason Terry,"Terry, Jason",J. Terry,jason-terry,1977-09-15T00:00:00,Arizona,USA,...,jason_terry,1999,2017,N,Y,Y,1999,1,10,N

In [103]:
col_names = {col:col.lower() for col in list(player_dim.columns)}
player_dim = player_dim.rename(columns=col_names)
player_dim.columns

Index(['player_key', 'first_name', 'last_name', 'display_first_last',
       'display_last_comma_first', 'display_fi_last', 'player_slug',
       'birthdate', 'school', 'country', 'last_affiliation', 'height',
       'weight', 'season_exp', 'jersey', 'position', 'rosterstatus',
       'games_played_current_season_flag', 'team_id', 'team_name',
       'team_abbreviation', 'team_code', 'team_city', 'playercode',
       'from_year', 'to_year', 'dleague_flag', 'nba_flag', 'games_played_flag',
       'draft_year', 'draft_round', 'draft_number', 'greatest_75_flag'],
      dtype='object')

In [105]:
#print to investigate values in each 
test = player_dim.iloc[0, :].to_dict()
print(test)

{'player_key': 1713, 'first_name': 'Vince', 'last_name': 'Carter', 'display_first_last': 'Vince Carter', 'display_last_comma_first': 'Carter, Vince', 'display_fi_last': 'V. Carter', 'player_slug': 'vince-carter', 'birthdate': '1977-01-26T00:00:00', 'school': 'North Carolina', 'country': 'USA', 'last_affiliation': 'North Carolina/USA', 'height': '6-6', 'weight': 220.0, 'season_exp': 23, 'jersey': 15.0, 'position': 'Guard-Forward', 'rosterstatus': 'Inactive', 'games_played_current_season_flag': 'N', 'team_id': 1610612761, 'team_name': 'Raptors', 'team_abbreviation': 'TOR', 'team_code': 'raptors', 'team_city': 'Toronto', 'playercode': 'vince_carter', 'from_year': 1998, 'to_year': 2019, 'dleague_flag': 'N', 'nba_flag': 'Y', 'games_played_flag': 'Y', 'draft_year': '1998', 'draft_round': '1', 'draft_number': '5', 'greatest_75_flag': 'N'}

In [107]:
"""
How data should be modified
1. remove the birth time from birthdate.
2. height to centimeters.
3. new column draft date to calculate days experience in league
4. delete position column as it will be in the game_fact table.
5. delete team columns as it is dynamic and represented in the team_dim table.
"""

'\nHow data should be modified\n1. remove the birth time from birthdate.\n2. height to centimeters.\n3. new column season experience in days.\n4. delete position column as it will be in the game_fact table.\n5. delete team columns as it is dynamic and represented in the team_dim table.\n6. new column of the draft date which can be used to calculate league experience in days.\n'

In [109]:
player_dim.describe()

,player_key,weight,season_exp,jersey,team_id,from_year,to_year
count,1.199000e+03,1197.000000,1199.000000,970.000000,1.199000e+03,1199.000000,1199.000000
mean,1.225161e+06,215.025063,5.991660,18.061856,1.312401e+09,2017.100083,2022.246038
std,6.534241e+05,24.185792,4.489639,16.613878,6.258596e+08,5.224508,2.837328
min,1.713000e+03,159.000000,0.000000,0.000000,0.000000e+00,1998.000000,2017.000000
25%,2.039340e+05,198.000000,3.000000,5.000000,1.610613e+09,2014.000000,2020.000000
50%,1.628994e+06,215.000000,4.000000,14.000000,1.610613e+09,2018.000000,2023.000000
75%,1.630552e+06,230.000000,8.000000,25.000000,1.610613e+09,2021.000000,2025.000000
max,1.642530e+06,311.000000,23.000000,99.000000,1.610613e+09,2024.000000,2025.000000

In [111]:
player_dim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1199 entries, 0 to 1198
Data columns (total 33 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   player_key                        1199 non-null   int64
 1   first_name                        1198 non-null   object
 2   last_name                         1199 non-null   object
 3   display_first_last                1199 non-null   object
 4   display_last_comma_first          1199 non-null   object
 5   display_fi_last                   1199 non-null   object
 6   player_slug                       1199 non-null   object
 7   birthdate                         1199 non-null   object
 8   school                            1198 non-null   object
 9   country                           1199 non-null   object
 10  last_affiliation                  1197 non-null   object
 11  height                            1199 non-null   object
 12  weight                            1197 non-null   float64
 13  season_exp                        1199 non-null   int64
 14  jersey                            970 non-null    float64
 15  position                          1199 non-null   object
 16  rosterstatus                      1199 non-null   object
 17  games_played_current_season_flag  1199 non-null   object
 18  team_id                           1199 non-null   int64
 19  team_name                         977 non-null    object
 20  team_abbreviation                 977 non-null    object
 21  team_code                         977 non-null    object
 22  team_city                         977 non-null    object
 23  playercode                        1199 non-null   object
 24  from_year                         1199 non-null   int64
 25  to_year                           1199 non-null   int64
 26  dleague_flag                      1199 non-null   object
 27  nba_flag                          1199 non-null   object
 28  games_played_flag                 1199 non-null   object
 29  draft_year                        1199 non-null   object
 30  draft_round                       1166 non-null   object
 31  draft_number                      1165 non-null   object
 32  greatest_75_flag                  1199 non-null   object
dtypes: float64(2), int64(5), object(26)
memory usage: 309.2+ KB

In [79]:
#1. remove the birth time from birthdate.
player_dim['birthdate'] = player_dim['birthdate'].apply(lambda datetime: datetime.split('T')[0])

In [117]:
#2. height to centimeters.
def feet_inch_to_cm(height):
    feet, inches = height.split('-')
    feet = int(feet)
    inches = int(inches)
    return 30.48 * feet + 2.54 * inches

player_dim['height'] = player_dim['height'].apply(feet_inch_to_cm)
test = player_dim[['display_first_last', 'height']].head()
print(test)

  display_first_last  height
0       Vince Carter  198.12
1     Jamal Crawford  195.58
2      Manu Ginobili  198.12
3      Dirk Nowitzki  213.36
4        Jason Terry  187.96

In [119]:
#3. new column draft date to calculate days experience in league
player_dim['from_year'].describe()

count    1199.000000
mean     2017.100083
std         5.224508
min      1998.000000
25%      2014.000000
50%      2018.000000
75%      2021.000000
max      2024.000000
Name: from_year, dtype: float64

In [139]:
path = "C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\draft_dates.xlsx"
draft_dates = pd.read_excel(path)
draft_dates.head()

   draft year  draft month  draft day
0        1998            6         24
1        1999            6         30
2        2000            6         28
3        2001            6         27
4        2002            6         26

In [157]:
dates = []
years = []
months = []
days = []
for year in draft_dates['draft year']:
    year = str(year)
    years.append(year)
for month in draft_dates['draft month']:
    month = str(month)
    if len(month) < 2:
        month = "0" + month
    months.append(month)
for day in draft_dates['draft day']:
    day = str(day)
    days.append(day)
for i in range(len(years) - 1):
    dates.append(years[i] + "-" + months[i] + "-" + days[i])

def draft_date_from_year(year):
    for date in dates:
        if date[:4] == str(year):
            return date

player_dim['draft_date'] = player_dim['draft_year'].apply(draft_date_from_year)
player_dim[['display_first_last', 'draft_date']].head()

  display_first_last  draft_date
0       Vince Carter  1998-06-24
1     Jamal Crawford  2000-06-28
2      Manu Ginobili  1999-06-30
3      Dirk Nowitzki  1998-06-24
4        Jason Terry  1999-06-30

In [159]:
#4. delete position column as it will be in the game_fact table.
player_dim.columns

Index(['player_key', 'first_name', 'last_name', 'display_first_last',
       'display_last_comma_first', 'display_fi_last', 'player_slug',
       'birthdate', 'school', 'country', 'last_affiliation', 'height',
       'weight', 'season_exp', 'jersey', 'position', 'rosterstatus',
       'games_played_current_season_flag', 'team_id', 'team_name',
       'team_abbreviation', 'team_code', 'team_city', 'playercode',
       'from_year', 'to_year', 'dleague_flag', 'nba_flag', 'games_played_flag',
       'draft_year', 'draft_round', 'draft_number', 'greatest_75_flag',
       'draft_date'],
      dtype='object')

In [163]:
player_dim.drop('position', axis=1, inplace=True)

In [165]:
#5. delete team columns as it is dynamic and represented in the team_dim table.
player_dim.drop(['team_id', 'team_name', 'team_abbreviation', 'team_code', 'team_city'], axis=1, inplace=True)
player_dim.columns

Index(['player_key', 'first_name', 'last_name', 'display_first_last',
       'display_last_comma_first', 'display_fi_last', 'player_slug',
       'birthdate', 'school', 'country', 'last_affiliation', 'height',
       'weight', 'season_exp', 'jersey', 'rosterstatus',
       'games_played_current_season_flag', 'playercode', 'from_year',
       'to_year', 'dleague_flag', 'nba_flag', 'games_played_flag',
       'draft_year', 'draft_round', 'draft_number', 'greatest_75_flag',
       'draft_date'],
      dtype='object')

In [185]:
#table made, save to computer
path = "C:\\Users\\oscar\\big_ahh_files\\DW model\\player_dim.csv"
player_dim.to_csv(path, index=False)

In [181]:
#next is creating the team_dim table
team_dim = pd.DataFrame(columns=['team_id', 'team_name'])
for team_name in arenas['team']:
    temp = all_games[all_games['team_name'] == team_name]
    temp = temp[['team_id', 'team_name']].head(1)
    team_dim = pd.concat([team_dim, temp], axis=0)
team_dim.head()

    team_id     team_name
0        23         Kings
73        1         Hawks
216      16  Timberwolves
303      21          Suns
379      17          Nets

In [191]:
#table made, save to computer
team_dim = team_dim.rename(columns={'team_id':'team_key', 'team_name':'team_name'})
path = "C:\\Users\\oscar\\big_ahh_files\\DW model\\team_dim.csv"
team_dim.to_csv(path, index=False)

In [227]:
#next arena_dim table
arenas.head()

,team,arena,arena_start,arena_coor,nearest_airport,airport_coor
0,Kings,Golden 1 Center,2016-10-01,38°34′49.3″N 121°29′58.6″W,Sacramento International Airport,38°41′44″N 121°35′27″W
1,Hawks,State Farm Arena,1999-10-01,33°45′26″N 84°23′47″W,Hartsfield-Jackson International Airport,33°38′12″N 84°25′41″W
2,Timberwolves,Target Center,1990-10-01,44°58′46″N 93°16′34″W,Minnesota-Saint Paul International Airport,44°52′55″N 093°13′18″W
3,Suns,Footprint Center,1992-10-01,33°26′45″N 112°4′17″W,Phoenix Sky Harbor International Airport,33°26′03″N 112°00′42″W
4,Nets,Barclays Center,2012-10-01,40°40′57.58″N 73°58′30.81″W,John F Kennedy International Airport,40°38′23″N 73°46′44″W

In [207]:
arenas.loc[0, 'arena_coor'].split("\xa0")

['38°34′49.3″N', '121°29′58.6″W']

In [235]:
arena_dim = pd.DataFrame({'arena_key':range(1,len(arenas['arena'].unique()) + 1)})
arena_dim.shape

(32, 1)

In [263]:
num_arenas = len(arenas['arena'].unique())
num_arenas += 1
arena_dim = pd.DataFrame()
for arena in arenas['arena'].unique():
    temp = arenas[arenas['arena'] == arena]
    temp = temp[['arena', 'arena_coor', 'nearest_airport', 'airport_coor']].head(1)
    arena_dim = pd.concat([arena_dim, temp], axis=0)

arena_dim['arena_lat'] = arena_dim['arena_coor'].apply(lambda x: x.split("\xa0")[0])
arena_dim['arena_long'] = arena_dim['arena_coor'].apply(lambda x: x.split("\xa0")[1])
arena_dim['airport_lat'] = arena_dim['airport_coor'].apply(lambda x: x.split("\xa0")[0])
arena_dim['airport_long'] = arena_dim['airport_coor'].apply(lambda x: x.split("\xa0")[1])
arena_dim['arena_key'] = range(1, arena_num)
print(arena_dim.shape)
arena_dim = arena_dim[[
    'arena_key', 'arena', 'arena_coor',
    'arena_lat', 'arena_long', 'nearest_airport',
    'airport_coor', 'airport_lat', 'airport_long'
]]
arena_dim = arena_dim.rename(columns = {'arena': 'arena_name'})
arena_dim.head()

(33, 9)

,arena_key,arena_name,arena_coor,arena_lat,arena_long,nearest_airport,airport_coor,airport_lat,airport_long
0,1,Golden 1 Center,38°34′49.3″N 121°29′58.6″W,38°34′49.3″N,121°29′58.6″W,Sacramento International Airport,38°41′44″N 121°35′27″W,38°41′44″N,121°35′27″W
1,2,State Farm Arena,33°45′26″N 84°23′47″W,33°45′26″N,84°23′47″W,Hartsfield-Jackson International Airport,33°38′12″N 84°25′41″W,33°38′12″N,84°25′41″W
2,3,Target Center,44°58′46″N 93°16′34″W,44°58′46″N,93°16′34″W,Minnesota-Saint Paul International Airport,44°52′55″N 093°13′18″W,44°52′55″N,093°13′18″W
3,4,Footprint Center,33°26′45″N 112°4′17″W,33°26′45″N,112°4′17″W,Phoenix Sky Harbor International Airport,33°26′03″N 112°00′42″W,33°26′03″N,112°00′42″W
4,5,Barclays Center,40°40′57.58″N 73°58′30.81″W,40°40′57.58″N,73°58′30.81″W,John F Kennedy International Airport,40°38′23″N 73°46′44″W,40°38′23″N,73°46′44″W

In [265]:
#completed table, save to computer
path = "C:\\Users\\oscar\\big_ahh_files\\DW model\\arena_dim.csv"
arena_dim.to_csv(path, index=False)

In [281]:
#arena fact table
arena_changes = arenas[['team', 'arena_start', 'arena']]
arena_changes = arena_changes.rename(columns={'team': 'team_name', 'arena_state': 'arena_start_date', 'arena': 'arena_name'})
teams = team_dim[['team_name', 'team_key']]
arenas = arena_dim[['arena_key', 'arena_name']]

arena_change_fact = pd.merge(arena_changes, teams, on='team_name', how='inner')
arena_change_fact = pd.merge(arena_change_fact, arenas, on='arena_name', how='inner')
arena_change_fact.columns

Index(['team_name', 'arena_start', 'arena_name', 'team_key', 'arena_key'], dtype='object')

In [289]:
arena_change_fact = arena_change_fact.drop(['arena_name', 'team_name'], axis=1)
arena_change_fact.head()

  arena_start team_key  arena_key
0  2016-10-01       23          1
1  1999-10-01        1          2
2  1990-10-01       16          3
3  1992-10-01       21          4
4  2012-10-01       17          5

In [295]:
#save to computer
arena_change_fact = arena_change_fact[['team_key', 'arena_key', 'arena_start']]
arena_change_fact = arena_change_fact.rename(columns={'arena_start': 'arena_start_date'})
path = "C:\\Users\\oscar\\big_ahh_files\\DW model\\arena_change_fact.csv"
arena_change_fact.to_csv(path, index=False)

In [37]:
#create game_fact table
print(all_games.iloc[0, :].to_dict())

{'Unnamed: 0': 0, 'game_id': 400975976, 'season': 2018, 'season_type': 2, 'game_date': '2018-04-11', 'game_date_time': '2018-04-11 22:30:00', 'athlete_id': 136, 'athlete_display_name': 'Vince Carter', 'team_id': 23, 'team_name': 'Kings', 'team_location': 'Sacramento', 'team_short_display_name': 'Kings', 'minutes': 25.0, 'field_goals_made': 5.0, 'field_goals_attempted': 8.0, 'three_point_field_goals_made': 2.0, 'three_point_field_goals_attempted': 3.0, 'free_throws_made': 0.0, 'free_throws_attempted': 0.0, 'offensive_rebounds': 0.0, 'defensive_rebounds': 3.0, 'rebounds': 3.0, 'assists': 1.0, 'steals': 0.0, 'blocks': 0.0, 'turnovers': 1.0, 'fouls': 0.0, 'plus_minus': '+14', 'points': 12.0, 'starter': False, 'ejected': False, 'did_not_play': False, 'reason': "COACH'S DECISION", 'active': False, 'athlete_jersey': 15.0, 'athlete_short_name': 'V. Carter', 'athlete_headshot_href': 'https://a.espncdn.com/i/headshots/nba/players/full/136.png', 'athlete_position_name': 'Guard', 'athlete_position_abbreviation': 'G', 'team_display_name': 'Sacramento Kings', 'team_uid': 's:40~l:46~t:23', 'team_slug': 'sacramento-kings', 'team_logo': 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png', 'team_abbreviation': 'SAC', 'team_color': '393996', 'team_alternate_color': '8e9090', 'home_away': 'home', 'team_winner': True, 'team_score': 96, 'opponent_team_id': 10, 'opponent_team_name': 'Rockets', 'opponent_team_location': 'Houston', 'opponent_team_display_name': 'Houston Rockets', 'opponent_team_abbreviation': 'HOU', 'opponent_team_logo': 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png', 'opponent_team_color': 'D40026', 'opponent_team_alternate_color': 'c4ced3', 'opponent_team_score': 83}

In [307]:
"""
Changes to be made to the hoopR game data to make the game_fact table
1. remove 'Unnamed: 0' column - index from data cleaning.
2. remove the game_date_time column and replace with new column for just time.
3. [removed]
4. athlete_id must be removed and new column player_key which matches the player_dim table must be created.
5. remove team_name column and rename team_id column to player_team_key.
6. remove other team columns that belong on the team_key table.
7. remove columns of player info that belong on player_dim table.
8. remove athlete_position_name column.
9. simplify athlete_position_abbreviation and rename it to player_position.
10. rename home_away column to home?
11. rename opponent_team_id to opposing_team_key
"""

"\nChanges to be made to the hoopR game data to make the game_fact table\n1. remove 'Unnamed: 0' column - index from data cleaning.\n2. remove the game_date_time column and replace with new column for just time.\n3. rename game_id column to game_key.\n4. athlete_id must be removed and new column player_key which matches the player_dim table must be created.\n5. remove team_name column and rename team_id column to player_team_key.\n6. remove other team columns that belong on the team_key table.\n7. remove columns of player info that belong on player_dim table.\n8. remove athlete_position_name column.\n9. simplify athlete_position_abbreviation and rename it to player_position.\n10. rename home_away column to home?\n11. rename opponent_team_id to opposing_team_key\n"

In [329]:
#1. remove 'Unnamed: 0' column - index from data cleaning.
game_fact = all_games.iloc[:, 1:]

#2. remove the game_date_time column and replace with new column for just time.
game_fact['time'] = game_fact['game_date_time'].apply(lambda x: x.split(" ")[1])
game_fact.loc[:5, 'time']

0    22:30:00
1    20:30:00
2    20:00:00
3    22:00:00
4    21:30:00
5    22:00:00
Name: time, dtype: object

In [331]:
game_fact = game_fact.drop('game_date_time', axis=1)

In [345]:
#4. athlete_id must be removed and new column player_key which matches the player_dim table must be created.
hoopR_to_nba_api = {}
id_table['hoopR_ID']
id_table['nba_api_ID']
for i in range(len(id_table['nba_api_ID'])):
    hoopR_to_nba_api[id_table['hoopR_ID'][i]] = id_table['nba_api_ID'][i]
game_fact['player_key'] = game_fact['athlete_id'].apply(lambda x: hoopR_to_nba_api[x])
game_fact[['player_key', 'athlete_id']]

        player_key  athlete_id
0             1713         136
1             1713         136
2             1713         136
3             1713         136
4             1713         136
...            ...         ...
262750     1642279     5211984
262751     1642279     5211984
262752     1642279     5211984
262753     1642279     5211984
262754     1642279     5211984

[262755 rows x 2 columns]

In [347]:
game_fact.drop('athlete_id', axis=1, inplace=True)

In [349]:
#5. remove team_name column and rename team_id column to player_team_key.
#6. remove other team columns that belong on the team_key table.
game_fact.columns

Index(['game_id', 'season', 'season_type', 'game_date', 'athlete_display_name',
       'team_id', 'team_name', 'team_location', 'team_short_display_name',
       'minutes', 'field_goals_made', 'field_goals_attempted',
       'three_point_field_goals_made', 'three_point_field_goals_attempted',
       'free_throws_made', 'free_throws_attempted', 'offensive_rebounds',
       'defensive_rebounds', 'rebounds', 'assists', 'steals', 'blocks',
       'turnovers', 'fouls', 'plus_minus', 'points', 'starter', 'ejected',
       'did_not_play', 'reason', 'active', 'athlete_jersey',
       'athlete_short_name', 'athlete_headshot_href', 'athlete_position_name',
       'athlete_position_abbreviation', 'team_display_name', 'team_uid',
       'team_slug', 'team_logo', 'team_abbreviation', 'team_color',
       'team_alternate_color', 'home_away', 'team_winner', 'team_score',
       'opponent_team_id', 'opponent_team_name', 'opponent_team_location',
       'opponent_team_display_name', 'opponent_team_abbreviation',
       'opponent_team_logo', 'opponent_team_color',
       'opponent_team_alternate_color', 'opponent_team_score', 'time',
       'player_key'],
      dtype='object')

In [353]:
game_fact = game_fact.rename(columns={'team_id': 'team_key'})
game_fact.drop([
    'team_name', 'team_location', 'team_short_display_name',
    'team_display_name', 'team_uid', 'team_slug', 'team_logo',
    'team_abbreviation', 'team_color', 'team_alternate_color',
    'opponent_team_name', 'opponent_team_location',
    'opponent_team_display_name', 'opponent_team_abbreviation',
    'opponent_team_logo', 'opponent_team_color',
    'opponent_team_alternate_color'
], axis=1, inplace=True)
#7. remove columns of player info that belong on player_dim table.
game_fact.drop([
    'athlete_display_name', 'athlete_jersey',
    'athlete_short_name', 'athlete_headshot_href',
], axis=1, inplace=True)

In [ ]:
#8. remove athlete_position_name column.
#9. simplify athlete_position_abbreviation and rename it to player_position.

In [321]:
#id_table[id_table['athlete'] == 'Vince Carter'
print(id_table.loc[id_table['athlete'] == 'Vince Carter', 'nba_api_ID'].iloc[0])

1713

In [305]:
len(all_games[all_games['athlete_id'] == 136]['athlete_position_abbreviation'].value_counts().values)
type(all_games['athlete_id'].unique())

numpy.ndarray

In [67]:
position = {}
for idx in all_games['athlete_id'].unique():
    positions = len(all_games[all_games['athlete_id'] == idx]['athlete_position_abbreviation'].value_counts().values)
    if positions > 1:
        position[idx] = all_games[all_games['athlete_id'] == idx]['athlete_position_abbreviation'].value_counts()

In [357]:
print(position[3244]) #Should be simplified because granularity across game records is inconsistent
print(position[2991230]) 
print(position[6462]) 
print(position[6427])

athlete_position_abbreviation
F     380
PF    174
Name: count, dtype: int64
athlete_position_abbreviation
PG    420
SG    172
Name: count, dtype: int64
athlete_position_abbreviation
F     363
SF    162
Name: count, dtype: int64
athlete_position_abbreviation
C    511
F     32
Name: count, dtype: int64

In [359]:
game_fact.drop('athlete_position_name', axis=1, inplace=True)
def simply_position(position):
    if position == 'PF' or position == 'SF':
        return 'F'
    if position == 'PG' or position == 'SG':
        return 'G'
    else:
        return position

game_fact = game_fact.rename(columns={'athlete_position_abbreviation':'player_position'})
game_fact['player_position'] = game_fact['player_position'].apply(simply_position)
game_fact.loc[:10, 'player_position']

'G'

In [365]:
#10. rename home_away column to home?
#11. rename opponent_team_id to opposing_team_key
game_fact = game_fact.rename(columns={'home_away': 'home?', 'opponent_team_id': 'opposing_team_key'})
game_fact.columns

Index(['game_id', 'season', 'season_type', 'game_date', 'team_key', 'minutes',
       'field_goals_made', 'field_goals_attempted',
       'three_point_field_goals_made', 'three_point_field_goals_attempted',
       'free_throws_made', 'free_throws_attempted', 'offensive_rebounds',
       'defensive_rebounds', 'rebounds', 'assists', 'steals', 'blocks',
       'turnovers', 'fouls', 'plus_minus', 'points', 'starter', 'ejected',
       'did_not_play', 'reason', 'active', 'player_position', 'home?',
       'team_winner', 'team_score', 'opposing_team_key', 'opponent_team_score',
       'time', 'player_key'],
      dtype='object')

In [367]:
game_fact = game_fact.rename(columns={'time': 'game_time'})
path = "C:\\Users\\oscar\\big_ahh_files\\DW model\\game_fact.csv"
game_fact.to_csv(path, index=False)

In [421]:
#next we need the IL_update_fact table
IL_update_fact = injuries[['Date', 'Acquired', 'Relinquished', 'Notes', 'player_id']]
print('Shape pre-null-value-removal', IL_update_fact.shape)
null_value = injuries.loc[0, 'Acquired']
r = IL_update_fact[IL_update_fact['Acquired'].isnull()]
a = IL_update_fact[IL_update_fact['Relinquished'].isnull()]

rows, cols = r.shape
values = ['r', ] * rows
r['relinquished/acquired'] = values
r.drop(['Acquired', 'Relinquished'], axis=1, inplace=True)

rows, cols = a.shape
values = ['a', ] * rows
a['relinquished/acquired'] = values
a.drop(['Acquired', 'Relinquished'], axis=1, inplace=True)

IL_update_fact = pd.concat([a, r], axis=0)
IL_update_fact = IL_update_fact.sort_values(by='Date')
print('Shape pre-null-value-removal', IL_update_fact.shape)

Shape pre-null-value-removal (25976, 5)
Shape pre-null-value-removal (25976, 4)

C:\Users\oscar\AppData\Local\Temp\ipykernel_20044\2721813697.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r['relinquished/acquired'] = values
C:\Users\oscar\AppData\Local\Temp\ipykernel_20044\2721813697.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r.drop(['Acquired', 'Relinquished'], axis=1, inplace=True)
C:\Users\oscar\AppData\Local\Temp\ipykernel_20044\2721813697.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['relinquished/acquired'] = values
C:\Users\oscar\AppData\Local\Temp\ipykernel_20044\2721813697.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a.drop(['Acquired', 'Relinquished'], axis=1, inplace=True)

In [423]:
IL_update_fact.head()

,Date,Notes,player_id,relinquished/acquired
3,2016-01-01,activated from IL,0,a
2,2016-01-01,placed on IL,4,r
1,2016-01-01,back spasms (DTD),19,r
0,2016-01-01,placed on IL recovering from surgery on right ...,133,r
11,2016-01-02,activated from IL,4,a

In [425]:
IL_update_fact = IL_update_fact[['player_id', 'Date', 'Notes', 'relinquished/acquired']]
injury_ids = list(IL_update_fact['player_id'].unique())

pst_to_nba_api = {}
id_table['pst_ID']
id_table['nba_api_ID']
for i in range(len(id_table['nba_api_ID'])):
    pst_to_nba_api[id_table['pst_ID'][i]] = id_table['nba_api_ID'][i]
IL_update_fact['player_key'] = IL_update_fact['player_id'].apply(lambda x: pst_to_nba_api[x])

IL_update_fact = IL_update_fact[['player_key', 'Date', 'Notes', 'relinquished/acquired']]
IL_update_fact = IL_update_fact.rename(columns={'Date': 'date', 'Notes': 'details'})
IL_update_fact.head()

,player_key,date,details,relinquished/acquired
3,203998,2016-01-01,activated from IL,a
2,1626147,2016-01-01,placed on IL,r
1,2734,2016-01-01,back spasms (DTD),r
0,2744,2016-01-01,placed on IL recovering from surgery on right ...,r
11,1626147,2016-01-02,activated from IL,a

In [427]:
path = "C:\\Users\\oscar\\big_ahh_files\\DW model\\IL_update_fact.csv"
IL_update_fact.to_csv(path, index=False)

In [429]:
player_dim.columns

Index(['player_key', 'first_name', 'last_name', 'display_first_last',
       'display_last_comma_first', 'display_fi_last', 'player_slug',
       'birthdate', 'school', 'country', 'last_affiliation', 'height',
       'weight', 'season_exp', 'jersey', 'rosterstatus',
       'games_played_current_season_flag', 'playercode', 'from_year',
       'to_year', 'dleague_flag', 'nba_flag', 'games_played_flag',
       'draft_year', 'draft_round', 'draft_number', 'greatest_75_flag',
       'draft_date'],
      dtype='object')

In [485]:
game_fact.columns

Index(['game_id', 'season', 'season_type', 'game_date', 'team_key', 'minutes',
       'field_goals_made', 'field_goals_attempted',
       'three_point_field_goals_made', 'three_point_field_goals_attempted',
       'free_throws_made', 'free_throws_attempted', 'offensive_rebounds',
       'defensive_rebounds', 'rebounds', 'assists', 'steals', 'blocks',
       'turnovers', 'fouls', 'plus_minus', 'points', 'starter', 'ejected',
       'did_not_play', 'reason', 'active', 'player_position', 'home?',
       'team_winner', 'team_score', 'opposing_team_key', 'opponent_team_score',
       'game_time', 'player_key'],
      dtype='object')

In [ ]:
#last table is daily_fact
from datetime import datetime, date, timedelta
rs_starts = [
    date(2017, 10, 17),
    date(2018, 10, 16),
    date(2019, 10, 22),
    date(2020, 12, 22),
    date(2021, 10, 19),
    date(2022, 10, 18),
    date(2023, 10, 24),
    date(2024, 10, 22)
]
rs_ends = [
    date(2018, 4, 11),
    date(2019, 4, 10),
    date(2020, 4, 15),
    date(2021, 4, 16),
    date(2022, 4, 10),
    date(2023, 4, 9),
    date(2024, 4, 14),
    date(2025, 4, 13)
]

In [479]:
player_dim.loc[player_dim['player_key'] == 1626147, 'draft_date'].values[0]

'2015-06-25'

In [919]:
from datetime import datetime, date, timedelta

table_start = string_to_date('2017-09-17')
table_end = string_to_date('2025-04-13')

def string_to_date(date_str):
    return datetime.strptime(date_str, "%Y-%m-%d")

def date_to_string(date):
    return date.strftime('%Y-%m-%d')

def player_last_game(player_key):
    player_games = game_fact.loc[game_fact['player_key'] == player_key, :]
    player_games = player_games.sort_values(by='game_date')
    date_str = player_games.tail(1)['game_date'].values[0]
    return string_to_date(date_str)

def player_draft_date(player_key):
    #date_str = player_dim.loc[player_dim['player_key'] == player_key, 'draft_date'].values[0]
    date_str = str(player_dim.loc[player_dim['player_key'] == player_key, 'from_year'].values[0]) + "-06-30"
    return string_to_date(date_str)

def player_birthdate(player_key):
    date_str = player_dim.loc[player_dim['player_key'] == player_key, 'birthdate'].values[0].split("T")[0]
    return string_to_date(date_str)

def player_window_start(player_key):
    draft_date = player_draft_date(player_key)
    if draft_date < table_start:
        return table_start
    else:
        return draft_date

def player_dates(player_key):
    window_end = player_last_game(player_key)
    window_start = player_window_start(player_key)

    days = []
    current_day = window_start
    while current_day != window_end:
        days.append(current_day)
        current_day += timedelta(days=1)
    days.append(window_end)
    return days

def team_on_player_date(player_key, date_str):
    player_games = game_fact.loc[game_fact['player_key'] == player_key, ['game_date', 'team_key']]
    return player_games.loc[player_games['game_date'] == date_str, 'team_key'].iloc[0]

def player_sparse_team_keys(player_key, player_dates):
    team_by_day = []
    
    for date in player_dates:
        date = date_to_string(date)
        if date in game_fact.loc[game_fact['player_key'] == player_key, 'game_date'].values:
            team_by_day.append(team_on_player_date(player_key, date))
        else:
            team_by_day.append(-1)
                
    return team_by_day

team_by_day = []

def populate_sparse(sparse_teams): #goes until it finds a non -1 key and fills all past ids and then resets
    current_stretch = []
    
    for i in range(len(sparse_teams)):
        current_stretch.append(i)
        if sparse_teams[i] != -1:
            for idx in current_stretch:
                sparse_teams[idx] = sparse_teams[i]
            current_stretch = []
            past_team_key = sparse_teams[i]
        elif i == len(sparse_teams) - 1: #fill up last few entries
            for idx in current_stretch:
                sparse_teams[idx] = past_team_key
        else:
            continue
    return sparse_teams

def difference_days(date2, date1): #difference between datetime objects in days
    difference = date2 - date1
    return difference.days

def all_days_age(player_key, player_dates):
    birthdate = player_birthdate(player_key)
    ages = []
    for date in player_dates:
        ages.append(difference_days(date, birthdate))

    return ages

def all_days_exp(player_key, player_dates):
    draft_date = player_draft_date(player_key)
    experience = []
    for date in player_dates:
        experience.append(difference_days(date, draft_date))

    return experience

def player_IL_dict(player_key):
    player_IL = IL_update_fact.loc[IL_update_fact['player_key'] == player_key, ['date', 'relinquished/acquired']].sort_values(by='date')
    dates = player_IL['date'].values
    ra = player_IL['relinquished/acquired'].values

    dates_to_ra = {}
    for i in range(len(dates)):
        dates_to_ra[dates[i]] = ra[i]

    if not dates_to_ra:
        return {'2017-09-01':'a'}
    else:
        return dates_to_ra

def prestatus(player_key):
    window_start = player_window_start(player_key) #draft day or (for older players) 2017-09-17
    IL_dict = player_IL_dict(player_key)
    update_dates = list(IL_dict.keys())
    oldest_IL_record = string_to_date(update_dates[0])

    if oldest_IL_record > window_start:
        return False

    update_dates = [string_to_date(date) for date in update_dates] #turn into datetime for comparison with current_day

    current_day = window_start
    while current_day not in update_dates:
        current_day = current_day - timedelta(days=1)

    current_day = date_to_string(current_day) #current_day to string to match the keys for the dict
    if IL_dict[current_day] == 'r':
        return True
    else:
        return False

def player_status_ls(player_key, player_dates):
    IL_dict = player_IL_dict(player_key)
    status = []
    current_status = prestatus(player_key)
    
    for date in player_dates:
        date = date_to_string(date)
        if date in list(IL_dict.keys()):
            if IL_dict[date] == 'r' and current_status == True:
                status.append(current_status)
                continue
            elif IL_dict[date] == 'r' and current_status == False:
                current_status = not current_status
                status.append(current_status)
            elif IL_dict[date] == 'a' and current_status == True:
                current_status = not current_status
                status.append(current_status)
            elif IL_dict[date] == 'a' and current_status == False:
                status.append(current_status)
                continue
        else:
            status.append(current_status)
    return status
        
    
    
#print(player_last_game(1626147))
#print(player_window_start(1626147))
#print(player_draft_date(1626147))
#print(player_birthdate(1626147))
#dates = player_dates(1626147)
#sparse = player_sparse_team_keys(1626147, dates)
#team_kys = populate_sparse(sparse)
#IL_status = player_status_ls(1626147, dates)
#age = all_days_age(1626147, dates)
#exp = all_days_exp(1626147, dates)
#print('REPORT')
#print('TEAM KEYS: ', len(team_kys))
#print('IL STATUS: ', len(IL_status))
#print('AGE: ', len(age))
#print('EXP: ', len(exp))

In [871]:
print(team_kys)
print(IL_status)
print(age)
print(exp)

[20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11]
[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

In [807]:
id_table.head(50).tail(5)

    hoopR_ID            athlete  nba_api_ID  pst_ID
45      2797    Marvin Williams      101107     197
46      2799       Lou Williams      101150      99
47      2806      Jose Calderon      101181     114
48      2983  LaMarcus Aldridge      200746      36
49      3005           Rudy Gay      200752      83

In [811]:
dates = player_dates(200746)
sparse = player_sparse_team_keys(200746, dates)
team_kys = populate_sparse(sparse)
IL_status = player_status_ls(200746, dates)
age = all_days_age(200746, dates)
exp = all_days_exp(200746, dates)
print('REPORT')
print('TEAM KEYS: ', len(team_kys))
print('IL STATUS: ', len(IL_status))
print('AGE: ', len(age))
print('EXP: ', len(exp))
print(team_kys)
print(IL_status)
print(age)
print(exp)

REPORT
TEAM KEYS:  1682
IL STATUS:  1682
AGE:  1682
EXP:  1682
[24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 111353, 111353, 111353, 111353, 111353, 111353, 111353, 111353, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 111353, 111353, 111353, 111353, 111353, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17]
[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, True, True, True, False, False, False, False, False, False, False, False, False, False, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, True, True, False, False, False, False, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

In [921]:
#make it real:
from tqdm import tqdm

def make_daily_player(player_key):
    dates = player_dates(player_key)

    player_id = [player_key, ] * len(dates)
    
    sparse = player_sparse_team_keys(player_key, dates)
    team_keys = populate_sparse(sparse)
    
    IL_status = player_status_ls(player_key, dates)
    age = all_days_age(player_key, dates)
    exp = all_days_exp(player_key, dates)

    return(player_id, team_keys, dates, age, exp, IL_status)

daily_fact = pd.DataFrame(columns=['player_key', 'team_key', 'date', 'age', 'experience', 'injured?'])
for idx in tqdm(id_table['nba_api_ID']):
    p, t, d, a, e, i, = make_daily_player(idx)
    temp = pd.DataFrame({
        'player_key': p,
        'team_key': t,
        'date': d,
        'age': a,
        'experience': e,
        'injured?': i
        })
    daily_fact = pd.concat([daily_fact, temp], axis=0)

print(daily_fact.shape)

  0%|          | 0/1199 [00:00<?, ?it/s]C:\Users\oscar\AppData\Local\Temp\ipykernel_20044\3095946797.py:29: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  daily_fact = pd.concat([daily_fact, temp], axis=0)
100%|██████████| 1199/1199 [47:30<00:00,  2.38s/it]

(1519374, 6)

In [913]:
player_dim['from_year'].unique()

array([1998, 2000, 2002, 1999, 2001, 2003, 2004, 2005, 2007, 2006, 2008,
       2010, 2009, 2012, 2011, 2017, 2015, 2019, 2016, 2014, 2013, 2018,
       2020, 2021, 2022, 2023, 2024], dtype=int64)

In [925]:
path = "C:\\Users\\oscar\\big_ahh_files\\DW model\\daily_fact.csv"
daily_fact.to_csv(path, index=False)